# Pre-commit that runs locally
fail_fast: false #все настроенные хуки будут запускаться, даже если предыдущие хуки обнаружили проблемы.

# проверяет yaml-ы
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
# обертка вокруг prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: '\.(yaml|yml)$'
# форматирование питон-кода
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3.11
# линтер на соответствие стилю PEP 8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
# Стандартизирует форматирование SQL-запросов
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.21.0
    hooks:
      - id: sqlfmt
        files: ^(models|analyses|tests)/.*.sql$